name: macOS
on: [push]
jobs:
  macOS:
    name: build-macos
    runs-on: macos-latest
    steps:
      - name: Installing dependencies (macOS)
        run: brew install ninja
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creating dependencies directory (Ubuntu)
        run: mkdir packages

      - name: Creating build directory (macOS)
        run: mkdir build
      - name: Running CMake (macOS)
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        working-directory: ${{ github.workspace }}/build
      - name: Build (macOS)
        run: cmake --build .
        working-directory: ${{ github.workspace }}/build
      - name: Tests (macOS)
        run: ctest
        working-directory: ${{ github.workspace }}/build